6071 - ET - Fix server inactive session timeout
z-open/zerv-ng-core pull request #18
Opened 2020-10-22 23:15 UTC by etelmon

FIx inactive session timeout.
The session will time out on the server side even if the app tab or browser is closed (workstation turned off), network is disconnected for the duration of the inactive timeout.

Run 
`npm test`

2020-10-26 22:45 UTC, Jacob-Friesen requested changes
There is a code question and a testing one.

2020-10-26 22:45 UTC, Jacob-Friesen commented on src/services/auth.service.js
> +        const lastNotif = Number(localStorage.lastNu || 0);
This should be `Number(localStorage.lastNu) || 0;` instead if the intent is to handle `localStorage.lastNu` being a non number non falsely value. Also, something like `localStorage.lastNotifyUser` would be clearer for a name.

2020-10-26 22:45 UTC, Jacob-Friesen commented on test/specs/auth.service.specs.js
> +                    var r = socketListeners[event](data, () => {});
There should be new tests/more test modifications for this functionality since it is a major change.

2020-10-27 13:17 UTC, etelmon commented on test/specs/auth.service.specs.js
> +                    var r = socketListeners[event](data, () => {});
If you remove this, the test will not pass.

2020-10-27 13:22 UTC, etelmon commented on src/services/auth.service.js
> +        const lastNotif = Number(localStorage.lastNu || 0);
This is minimum code. Functionality would crash if the value is not correct. but the localStorage value is trusted as it is only set by the application itself, not a human.

On purpose the name of the var is unclear -> Hackers love meaningful variable in the localStorage!

2020-10-28 21:45 UTC, Jacob-Friesen commented on src/services/auth.service.js
> +        const lastNotif = Number(localStorage.lastNu || 0);
ok. As explained though the naming doesn't really help for security. Security needs to be backend based.

2020-10-28 22:11 UTC, Jacob-Friesen commented on test/specs/auth.service.specs.js
> +                    var r = socketListeners[event](data, () => {});
PR is https://github.com/zimit-io/zimit-webapp/pull/4837

2020-10-28 22:11 UTC, Jacob-Friesen approved these changes

2020-10-29 22:56 UTC, merged